services:
  planship-nuxt-example-app:
    build:
      context: .
    command: pnpm dev
    restart: always
    ports:
      - "3000:3000"
      - "24678:24678"
    networks:
      - planship-dev-network
    volumes:
      - ./app:/app/app

networks:
  planship-dev-network:
    name: planship-dev-network
